### ISSUE TITLE
vue-router 4中设置 router-link  禁用 disabled 的解决方案

### ISSUE THREAD

**Issue by shizhihuaxu** [shizhihuaxu/documents#53]
[参见官方文档](https://router.vuejs.org/zh/guide/advanced/extending-router-link)
``` vue
<router-link
    :to='{
      path: '/'
      query:  {
         query: 'something'
      }
    }'
    custom // important
    v-slot='{ href }'>
    <a
      v-bind='$attrs'
      :class='{ disabled: disabled }'
      target='_blank'
      :href='disabled ? null : href'>
        <slot /> // your slot
     </a>
</router-link>

```

``` css 
.disabled {
    cursor: not-allowed;
    color: your disabled color
}
```
